language: java
jdk: openjdk10
script: echo "Success!"
deploy:
  provider: heroku
  api_key:
    secure: BerTcdewCrnvFujwhxuPbmMcwnOzGYNbnp5bYRPK+KPvbHjqqj7aYJFnE1qBRiGCw7oO9EOYgieZNeEHwtDJ7ZOkvJ99M0FstK7DAS/fUAsV1JKnoxorOvk1WT9TkuJ/RcjwICuxCa675fkhjJYPoz0R/tYHcArGxrxAm1jnnuM9gqD6Nmu0FG410lEahXWjhi7Uy2BCM9l9SLZoaltwOG1VMdIJENLYS0qFmnidkDTJ3zSEpzmiYsBYvb7tkbNuMNLNXH9CjdczNedJ9thPfgKskb/0MA61UDAelSqJEiFme1zZGg7uYxdJ+pAtVlFgs8Ai7GdfGlFPx4BBAA6jwDkZoNJsfYRVNTJxLlAXR9woHrvaX7msF+7DOJFwSBwG7zorilPQKzO+bbv8A0vhkWAvF5E4YG6cshMbgKzEXHDpdGNvMytehLMKN1zVT0pxQ5Bmltd9thWG2QiP3gq0LnOctnRHunNWatqG58l61V+HXKWmCbw6cL/t7iR1xYiHplVEAmwLQ3zGZ6whrkN+q77cxzSEeeu5JGZ7OGeNrK3Dm+70AWhvUcXzFMgcwPK43XiWRBQnYNrTfRA99t/J0x1HmzRFjV0K5zX3QMjEHUNNVsv57d5IrZYUByN4wf2bDRAkrBAPmxMMYpqu5zLCKb1OJRjvVqtTE2+9dtaVpa4=
  run:
  - cd server-product
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  on:
    all_branches: true
