language: java
jdk: openjdk10
script: echo "Success!"
deploy:
  provider: heroku
  api_key:
    secure: V8/U8S6hmocD+lfKaKQt6kNQlqkYufdGn/sNPSwRYjtLrDv2cgnsW1PHBm3yttKeztJN3+QSiD6qP9M+oB+xznoYntha4av6LKyUOwoxu/athnT8zMKMehQ8Gtkz76fliB5v3I9reMffx1seWUEm5M8LWYm9yUZ1dyytvzAQueLOKfEqqkFeVjWw/z7bjjSc7KrXvoUuYFF++dhRp4WUesP7seesj/+z+txlGvC25jAdTG8FYs3P1DWU2A26ixadCWoOsgXCIuDc1RibbLYRZNtS1VJ0Z4XksfvVUMW6HHnCkjYsFJ+f2Sc9J7q2hsz+wUaYsWfeYzef/1cWFwOatbxJrS53vdVteN9mf0g9c+jL6R0RXasMKzP7BaIWx2n6X/HxweRHlfO4ZGJKO6/fGR6fyIawIHxXOlcGVKGThDgqqayRqzR6en+rHgwNBcTfaoeq39sdrJXGF0O+8HFzIRoGSJa05iuoEAseF7ibkFjXzCmhyyZNrXVq5SdfKCB0SPt3LCTolYoE6EKn8AIDT/xr6nUKUxlZIu8jaiqVjtemLLLFYM+/nY2id2HjS1lj+3RA6GHr1stM2AnOZGGrdtq8cIlj5tawGjWEqW8IVL/sQT2buVuWvv11j0oPbOmSHaIccsns6fENhwC8Nb/OaQh+7/TIb4crd03rPnSLfTI=
  run:
  - cd server-product
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  on:
    all_branches: true
