language: java
jdk: openjdk10
script: echo "Success!"
deploy:
  provider: heroku
  api_key:
    secure: nQYovmItDD5fUT32b/NhgFK++D8o3IKX2SSLY1y7UJf9+eYGkCThmMXGGY7qp7XjNzbOor+J1lrKp007/2/ne/EEL9eBQJWio3JRQop4MRhWnr5/lpxX5kGplj8OGeJIckzP9He8Mzny8p7tbgjq8dJ/AENp3xZIS39vfNE0SF7MAAdJ8t9kSEVE/8Zx7/MahZs7ISzyWcM/7XYHc6hqXFmS6ii52zUjzOdR+Arpbxn5pw8I+q9WO7MfoAUlaq/8bGBTo0MB01s//kotEPOVmkGg3l3uxHXokK8SDAb819ATQXz/hk1EpWPFDZaFvbJJ+f9cy+QJvxvyuhQmISuXlli5oxGU2/V9pw+DxoLrfvRsq1l2qI3UNlAHIqVt7RM1ZbPpo3x2H+PPUzQuopvj3Eiw2AgmO2IW1dCMH+I7K1dtXWU3bI0ZkfLNXdjl3eXNTb5eKtZlPphUC3SnRxbtK/Nw+ND4RXKCLIx+RIh8PEKDl8MiBiIiPO7b/WSZtFLiSPji48LtK8VzXiXLL435YmU5+B+BpFP3zTTKcvGmTfFkyOzQL1yvfOHM12AOaVXmb/fmxvRIiHOWFi3ZcVeVILi0+5EhtPyPuwkYlUG/0Z4NTLQwWzE5Zi/Eb0VVbNYFDIqsFpTzAwACKrjhOsKJep5MwuemwbP/CxSHxPpsbSI=
  app: quality-onedev
  run:
    - cd server-product
    - mvn exec:java -Dexec.mainClass="io.onedev.commons.launcher.bootstrap.Bootstrap"
  on:
    repo: xishec/onedev
    branch: main
  skip_cleanup: "true"
