language: java

jdk: openjdk10
script:
  - jdk_switcher use openjdk10
  - # do stuff with OpenJDK 10
  - export JAVA_HOME=$HOME/openjdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh --install openjdk11 --target $JAVA_HOME
  - # do stuff with open OpenJDK 11

deploy:
  provider: heroku
  api_key:
		secure: "c5ef4eee-8e09-4a01-a97b-793bb80e3b18"

	run:
		- "cd server-product"
		- "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
